### PR TITLE
Track last read leaf in book

### PR DESCRIPTION
**Pull request by afcapel**
@jzimdars this adds a class `toc__leaf--last-read` to the last leaf read in the TOC.

https://github.com/basecamp/workbook/assets/150107/4b364840-ac82-461d-8d40-8c371824aa10

Next, I'll implement the overall position in the book in the books index.

Do you need anything else for the indicator in the TOC?

### CODE REVIEW

**Comment by afcapel** [comment]
I've also pushed a change to move the bookmarks in the books index.

https://github.com/basecamp/workbook/assets/150107/2878502b-aeb4-45ad-954b-ba756f98fdc6

@jzimdars we also want to change the book link so when you re-open a book you go to the last read page, is that correct?

**Comment by jzimdars** [comment]
> @jzimdars we also want to change the book link so when you re-open a book you go to the last read page, is that correct?

Yeah. I was originally thinking you'd click on the bookmark to do that but your idea is clearer. I mean, why whouldn't you want to go back to where you left off? Might as well make that the golden path.

**Comment by jzimdars** [comment]
> Do you need anything else for the indicator in the TOC?

Nope. That's perfect

**Comment by afcapel** [comment]
Cool, [I've added a link from the book cover on the books index page you go to the last page you read](https://github.com/basecamp/workbook/pull/92/commits/27c0396ae7cad20fe05ebed1bea28bc0ce5cad12), or to the book index, if you haven't started it yet.

We load the bookmark dynamically, but we want to make the whole book cover clickable so I've added a new `.stretched-link` class to allow a link target its container. This is inspired in [Bootstrap's utility class](https://getbootstrap.com/docs/5.3/helpers/stretched-link/). This allows us to implement the linking without any extra JS, but let me know if there's any drawbacks to the CSS only approach and we can re-think the solution.

**Pull request merged**
